### ISSUE TITLE
what is this?

### ISSUE THREAD

**Issue by Hezuikn** [Pure-Peace/simple-rijndael#1]

**Comment by Pure-Peace** [comment]
The Advanced Encryption Standard (AES), also known by its original name Rijndael
https://en.wikipedia.org/wiki/Advanced_Encryption_Standard

**Comment by Hezuikn** [comment]
what is score data and why does osu encrypt it with aes and why does it use weird block and key sizes and why did you first implement it in python?

**Comment by Pure-Peace** [comment]
That in itself is a strange question. As far as I know, osu the game originally used php as the backend, and from there it used rijndael encryption. Later I decided to implement the osu backend using rust, but couldn't find an implementation of the 256bit blocks rijndael encryption algorithm in rust, so I made one myself.

**Comment by Hezuikn** [comment]
grep --text sex /dev/random --color; hehe
